// PROJECTS
export const SET_PROJECTS = "SET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const SET_PROJECT = "SET_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SET_POPUP_IS_OPEN = "SET_POPUP_IS_OPEN";
export const SET_POPUP_STATUS = "SET_POPUP_STATUS";
